/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package celsiuscalculator;

import javax.swing.JOptionPane;

/**
 *
 * @author Jenna
 */
public class CFCalculator extends javax.swing.JFrame {

    /**
     * Creates new form CFCalculator
     */
    public CFCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tempCalculator = new javax.swing.ButtonGroup();
        lblEnterTemp = new javax.swing.JLabel();
        lblCalculatedTemp = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        btnCalculateTemp = new javax.swing.JButton();
        lblTempResult = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rboFahrenheitToCelsius = new javax.swing.JRadioButton();
        rboCelsiusToFahrenheit = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEnterTemp.setText("Enter temperature: ");

        lblCalculatedTemp.setText("     ");

        btnCalculateTemp.setText("Calculate Temperature");
        btnCalculateTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateTempActionPerformed(evt);
            }
        });

        lblTempResult.setText("Temperature: ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Temperature Conversion: "));

        tempCalculator.add(rboFahrenheitToCelsius);
        rboFahrenheitToCelsius.setSelected(true);
        rboFahrenheitToCelsius.setText("Fahrenheit to Celsius");
        rboFahrenheitToCelsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboFahrenheitToCelsiusActionPerformed(evt);
            }
        });

        tempCalculator.add(rboCelsiusToFahrenheit);
        rboCelsiusToFahrenheit.setText("Celsius to Fahrenheit");
        rboCelsiusToFahrenheit.setToolTipText("");
        rboCelsiusToFahrenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rboCelsiusToFahrenheitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rboCelsiusToFahrenheit)
                    .addComponent(rboFahrenheitToCelsius))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rboFahrenheitToCelsius)
                .addGap(18, 18, 18)
                .addComponent(rboCelsiusToFahrenheit)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblTempResult, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCalculatedTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnCalculateTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnterTemp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTemperature))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterTemp)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalculateTemp)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTempResult)
                    .addComponent(lblCalculatedTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateTempActionPerformed
        
        try {
        double temperature = Double.parseDouble(txtTemperature.getText());
        lblCalculatedTemp.setText(String.valueOf(tcs.calculateTemp(temperature)));
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Cannot accept letters!");
        }
        
    }//GEN-LAST:event_btnCalculateTempActionPerformed

    private void rboFahrenheitToCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboFahrenheitToCelsiusActionPerformed
        TemperatureCalculationStrategy fahrenheit = new FahrenheitCalculator();
        fahrenheit.setTempCalcStrategy(fahrenheit);
    }//GEN-LAST:event_rboFahrenheitToCelsiusActionPerformed

    private void rboCelsiusToFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rboCelsiusToFahrenheitActionPerformed
        TemperatureCalculationStrategy celsius = new CelsiusCalculator();
        celsius.setTempCalcStrategy(celsius);
    }//GEN-LAST:event_rboCelsiusToFahrenheitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CFCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CFCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CFCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CFCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CFCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateTemp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCalculatedTemp;
    private javax.swing.JLabel lblEnterTemp;
    private javax.swing.JLabel lblTempResult;
    private javax.swing.JRadioButton rboCelsiusToFahrenheit;
    private javax.swing.JRadioButton rboFahrenheitToCelsius;
    private javax.swing.ButtonGroup tempCalculator;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}
